apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: map-service
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: map-service
    app.kubernetes.io/part-of: dc-metro-map
  name: map-service
  namespace: user1-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: map-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: map-service
    spec:
      containers:
      - image: quay.io/jduimovich0/dc-metro-map@sha256:89489e5637f540452e1e9e1ae6ba3ec1d8dfb8e2220fc5fc8e4d669a9043b09c
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8080
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 512Mi
status: {}
